"""modelo de datos operativos: catalogo completo de variables y operacion abierta/cerrada

Revision ID: 11ffb005c5e9
Revises: 7004761949fd
Create Date: 2026-08-24 23:16:31.234075

"""
import sqlalchemy as sa
from alembic import op

revision = '11ffb005c5e9'
down_revision = '7004761949fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajuste manual: Alembic no detecta renombres y propuso drop + add de
    # 'date'. Es la misma columna con otro nombre, asi que se renombra para no
    # perder las filas ya cargadas. La duracion pasa a derivarse de
    # ended_at - started_at (ver Operation en historicals/models.py).
    op.alter_column('operations', 'date', new_column_name='started_at')
    op.add_column('operations', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_operations_date'), table_name='operations')
    op.create_index(op.f('ix_operations_started_at'), 'operations', ['started_at'], unique=False)
    op.drop_column('operations', 'duration_minutes')
    op.add_column('reactor_samples', sa.Column('flu_neu', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('tem_nuc', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('niv_mod', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('tem_pil', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('pre_pri', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('cau_ref', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('niv_pil', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_br2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_br3', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_br4', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_brs', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('per_rea', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('dos_sal', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('dos_pil', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('dos_ven', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('tem_amb', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('hum_amb', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('pre_atm', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('vol_det1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('vol_det2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('fre_det', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('rui_det', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ten_red', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('cor_bom', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('est_bom', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('cau_ven', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('pre_ven', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('con_ph', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('con_o2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('con_con', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_reactor_samples_operation_id'), table_name='reactor_samples')
    op.drop_index(op.f('ix_reactor_samples_timestamp'), table_name='reactor_samples')
    op.create_index('ix_reactor_samples_operation_id_timestamp', 'reactor_samples', ['operation_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reactor_samples_operation_id_timestamp', table_name='reactor_samples')
    op.create_index(op.f('ix_reactor_samples_timestamp'), 'reactor_samples', ['timestamp'], unique=False)
    op.create_index(op.f('ix_reactor_samples_operation_id'), 'reactor_samples', ['operation_id'], unique=False)
    op.drop_column('reactor_samples', 'con_con')
    op.drop_column('reactor_samples', 'con_o2')
    op.drop_column('reactor_samples', 'con_ph')
    op.drop_column('reactor_samples', 'pre_ven')
    op.drop_column('reactor_samples', 'cau_ven')
    op.drop_column('reactor_samples', 'est_bom')
    op.drop_column('reactor_samples', 'cor_bom')
    op.drop_column('reactor_samples', 'ten_red')
    op.drop_column('reactor_samples', 'rui_det')
    op.drop_column('reactor_samples', 'fre_det')
    op.drop_column('reactor_samples', 'vol_det2')
    op.drop_column('reactor_samples', 'vol_det1')
    op.drop_column('reactor_samples', 'pre_atm')
    op.drop_column('reactor_samples', 'hum_amb')
    op.drop_column('reactor_samples', 'tem_amb')
    op.drop_column('reactor_samples', 'dos_ven')
    op.drop_column('reactor_samples', 'dos_pil')
    op.drop_column('reactor_samples', 'dos_sal')
    op.drop_column('reactor_samples', 'per_rea')
    op.drop_column('reactor_samples', 'pos_brs')
    op.drop_column('reactor_samples', 'pos_br4')
    op.drop_column('reactor_samples', 'pos_br3')
    op.drop_column('reactor_samples', 'pos_br2')
    op.drop_column('reactor_samples', 'niv_pil')
    op.drop_column('reactor_samples', 'cau_ref')
    op.drop_column('reactor_samples', 'pre_pri')
    op.drop_column('reactor_samples', 'tem_pil')
    op.drop_column('reactor_samples', 'niv_mod')
    op.drop_column('reactor_samples', 'tem_nuc')
    op.drop_column('reactor_samples', 'flu_neu')
    # La duracion no se puede reconstruir para una operacion abierta, asi que
    # se recrea con default 0 (y se lo quita despues, para que la columna
    # vuelva a quedar como estaba en la revision anterior).
    op.add_column('operations', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text('0')))
    op.alter_column('operations', 'duration_minutes', server_default=None)
    op.drop_index(op.f('ix_operations_started_at'), table_name='operations')
    op.drop_column('operations', 'ended_at')
    op.alter_column('operations', 'started_at', new_column_name='date')
    op.create_index(op.f('ix_operations_date'), 'operations', ['date'], unique=False)
    # ### end Alembic commands ###
