"""catalogo real de senales del RA-0

Reemplaza las 33 columnas del catalogo provisional (sacado del mock del
prototipo de frontend) por las 34 senales reales del RA-0, agrupadas por
subsistema del I&C: SA1/SA2 arranque, SM1/SM2 marcha, SMP lineal, SP2
proteccion, SMA monitores de area, SCM circuito de moderador, SBC barras de
control, SSO supervision. Ver tarea 3.9 y variable_catalog.py.

ATENCION: las columnas viejas se eliminan, asi que las muestras ya cargadas
pierden sus valores (las filas de `reactor_samples` quedan con las columnas
nuevas en NULL). No hay forma de convertirlas: no existe correspondencia entre
las variables inventadas y las senales reales. En desarrollo la via limpia es
regenerar los datos con scripts/db/seed.py.

Revision ID: 8a9c3062a7f0
Revises: a1c3f7d2e910
Create Date: 2026-10-01 21:23:10.028312

"""
import sqlalchemy as sa
from alembic import op

revision = '8a9c3062a7f0'
down_revision = 'a1c3f7d2e910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactor_samples', sa.Column('loga1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ta1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('loga2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ta2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('logm1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('tm1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('logm2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('tm2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('lcm4', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('linm4', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ndcm4', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('masc', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('mabt', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('marr', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('matm', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('maae', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ndsc', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ndbt', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ndrr', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ndtm', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('ndae', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('tt1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('tn1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('nt1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('nn1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('qin', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('qtm', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('qrd', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('posbc1', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('posbc2', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('posbc3', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('posbc4', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('reactm4', sa.Float(), nullable=True))
    op.add_column('reactor_samples', sa.Column('potm4', sa.Float(), nullable=True))
    op.drop_column('reactor_samples', 'pre_atm')
    op.drop_column('reactor_samples', 'con_o2')
    op.drop_column('reactor_samples', 'cor_bom')
    op.drop_column('reactor_samples', 'rui_det')
    op.drop_column('reactor_samples', 'vol_det1')
    op.drop_column('reactor_samples', 'pre_pri')
    op.drop_column('reactor_samples', 'est_bom')
    op.drop_column('reactor_samples', 'flu_neu')
    op.drop_column('reactor_samples', 'ten_red')
    op.drop_column('reactor_samples', 'per_rea')
    op.drop_column('reactor_samples', 'cau_ref')
    op.drop_column('reactor_samples', 'con_ph')
    op.drop_column('reactor_samples', 'tem_pil')
    op.drop_column('reactor_samples', 'pos_brs')
    op.drop_column('reactor_samples', 'dos_ven')
    op.drop_column('reactor_samples', 'pot_nuc')
    op.drop_column('reactor_samples', 'con_con')
    op.drop_column('reactor_samples', 'pos_br1')
    op.drop_column('reactor_samples', 'niv_pil')
    op.drop_column('reactor_samples', 'vol_det2')
    op.drop_column('reactor_samples', 'niv_mod')
    op.drop_column('reactor_samples', 'hum_amb')
    op.drop_column('reactor_samples', 'cau_ven')
    op.drop_column('reactor_samples', 'dos_pil')
    op.drop_column('reactor_samples', 'pre_ven')
    op.drop_column('reactor_samples', 'dos_sal')
    op.drop_column('reactor_samples', 'pos_br3')
    op.drop_column('reactor_samples', 'rea_neu')
    op.drop_column('reactor_samples', 'pos_br4')
    op.drop_column('reactor_samples', 'fre_det')
    op.drop_column('reactor_samples', 'tem_amb')
    op.drop_column('reactor_samples', 'tem_nuc')
    op.drop_column('reactor_samples', 'pos_br2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactor_samples', sa.Column('pos_br2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('tem_nuc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('tem_amb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('fre_det', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_br4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('rea_neu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_br3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('dos_sal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pre_ven', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('dos_pil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('cau_ven', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('hum_amb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('niv_mod', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('vol_det2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('niv_pil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_br1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('con_con', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pot_nuc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('dos_ven', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pos_brs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('tem_pil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('con_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('cau_ref', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('per_rea', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('ten_red', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('flu_neu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('est_bom', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pre_pri', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('vol_det1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('rui_det', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('cor_bom', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('con_o2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reactor_samples', sa.Column('pre_atm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('reactor_samples', 'potm4')
    op.drop_column('reactor_samples', 'reactm4')
    op.drop_column('reactor_samples', 'posbc4')
    op.drop_column('reactor_samples', 'posbc3')
    op.drop_column('reactor_samples', 'posbc2')
    op.drop_column('reactor_samples', 'posbc1')
    op.drop_column('reactor_samples', 'qrd')
    op.drop_column('reactor_samples', 'qtm')
    op.drop_column('reactor_samples', 'qin')
    op.drop_column('reactor_samples', 'nn1')
    op.drop_column('reactor_samples', 'nt1')
    op.drop_column('reactor_samples', 'tn1')
    op.drop_column('reactor_samples', 'tt1')
    op.drop_column('reactor_samples', 'ndae')
    op.drop_column('reactor_samples', 'ndtm')
    op.drop_column('reactor_samples', 'ndrr')
    op.drop_column('reactor_samples', 'ndbt')
    op.drop_column('reactor_samples', 'ndsc')
    op.drop_column('reactor_samples', 'maae')
    op.drop_column('reactor_samples', 'matm')
    op.drop_column('reactor_samples', 'marr')
    op.drop_column('reactor_samples', 'mabt')
    op.drop_column('reactor_samples', 'masc')
    op.drop_column('reactor_samples', 'ndcm4')
    op.drop_column('reactor_samples', 'linm4')
    op.drop_column('reactor_samples', 'lcm4')
    op.drop_column('reactor_samples', 'tm2')
    op.drop_column('reactor_samples', 'logm2')
    op.drop_column('reactor_samples', 'tm1')
    op.drop_column('reactor_samples', 'logm1')
    op.drop_column('reactor_samples', 'ta2')
    op.drop_column('reactor_samples', 'loga2')
    op.drop_column('reactor_samples', 'ta1')
    op.drop_column('reactor_samples', 'loga1')
    # ### end Alembic commands ###
